[colors]
background = #1f232b
foreground = #d8dee9
accent = #88c0d0
warning = #ebcb8b
urgent = #bf616a

[bar/main]
width = 100%
height = 28
bottom = true
background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 1
padding-right = 1
module-margin = 2
separator = |
separator-foreground = ${colors.accent}
font-0 = JetBrainsMono Nerd Font Mono:style=Regular:pixelsize=13;2
font-1 = Font Awesome 7 Free Solid:style=Solid:pixelsize=13;2
modules-left = i3
modules-right = cpu net date

[module/cpu]
type = custom/script
exec = ~/.config/regolith3/polybar_top/cpu-usage.sh
interval = 2
label = %output%

# [module/i3]
# type = internal/i3
# index-sort = true
# strip-wsnumbers = true
# wrapping-scroll = false

[module/net]
type = custom/script
exec = ~/.config/regolith3/polybar_top/net-traffic.sh
interval = 2
label = %output%

[module/date]
type = internal/date
date = %a %d %b %H:%M
label =   %date%
label-foreground = ${colors.accent}
