#!/usr/bin/env bash
# desc: ed25519 keys for GitHub/GitLab/Bitbucket + ~/.ssh/config.d/dotfiles
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"
. "$DOTFILES/lib/os.sh"

refuse_root

ssh_dir="$HOME/.ssh"
generated="$ssh_dir/config.d/dotfiles"
# name  hostname
HOSTS=("github github.com" "gitlab gitlab.com" "bitbucket bitbucket.org")

have ssh-keygen || pkg_install openssh-client
run mkdir -p "$ssh_dir/config.d"
run chmod 700 "$ssh_dir"

config="# Generated by dotfiles/setup/ssh-keys.sh -- re-run it instead of editing.
"
for entry in "${HOSTS[@]}"; do
  read -r name host <<<"$entry"
  key="$ssh_dir/$name"
  if [ ! -f "$key" ] && [ -t 0 ]; then
    read -r -p "Create an SSH key for $host? [y/N] " ans
    if [ "$ans" = y ] || [ "$ans" = Y ]; then
      run_tty ssh-keygen -t ed25519 -C "$(whoami)@$(hostname)" -f "$key"
      log "add this public key to $host:"; cat "$key.pub"
    fi
  fi
  [ -f "$key" ] || continue
  run chmod 600 "$key"
  # ${name}_dotfile keeps remotes created by the old scripts working
  config+="
Host $host
  HostName $host
  User git
  IdentityFile ~/.ssh/$name
  IdentitiesOnly yes
"
done

if [ "$DRY_RUN" = 1 ]; then
  printf '   [dry-run] write %s\n' "$generated"
elif ! printf '%s' "$config" | cmp -s - "$generated"; then
  printf '%s' "$config" > "$generated"
  chmod 600 "$generated"
  ok "wrote $generated"
fi

# Include must come before any Host block, so it goes at the top of ~/.ssh/config
include="Include config.d/*"
if ! { [ -f "$ssh_dir/config" ] && grep -qxF "$include" "$ssh_dir/config"; }; then
  if [ "$DRY_RUN" != 1 ]; then
    { printf '%s\n\n' "$include"; cat "$ssh_dir/config" 2>/dev/null || true; } > "$ssh_dir/config.new"
    mv "$ssh_dir/config.new" "$ssh_dir/config"
  fi
  ok "added '$include' to ~/.ssh/config"
fi
run chmod 600 "$ssh_dir/config"
